### ISSUE TITLE
The app crashed when I click on an option after denying the access permission

### ISSUE THREAD

**Issue by sagorahmed** [michpohl/Loopy#3]
#### Expected behavior
I expected that I could click on every option after denying access permission.

#### Actual behavior
When I tried to click on "Browse music library" after denying the access permission, then the app crashed.

#### How to reproduce
**1.** If your phone has already this app installed then revoke the access permission from your phone's settings or reinstall this after uninstalling.
**2.** Your phone will ask you to grant all permission, click on "DENY".
**3.** Then go to this app's options and click on "Browse music library".
**4.** See error.

* App version: 0.9
* Operating system: Android 6.0.1

#### Logcat
```
05-07 13:28:08.357  7350  7350 D AndroidRuntime: Shutting down VM

05-07 13:28:08.367  7350  7350 E AndroidRuntime: FATAL EXCEPTION: main

05-07 13:28:08.367  7350  7350 E AndroidRuntime: Process: de.michaelpohl.loopy, PID: 7350

05-07 13:28:08.367  7350  7350 E AndroidRuntime: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/audio/albums from pid=7350, uid=10424 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1620)

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:502)

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:445)

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at de.michaelpohl.loopy.model.DataRepository.getAlbumTitles(DataRepository.kt:5)

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at de.michaelpohl.loopy.ui.main.filebrowser.AlbumBrowserFragment.onCreate(AlbumBrowserFragment.kt:2)

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:64)

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:24)

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:11)

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:44)

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:10)

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:4)

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:1)

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

05-07 13:28:08.367  7350  7350 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by michpohl** [comment]
Hi, thanks for bringing this to my attentions. I just fixed this bug on the development branch in this commit: https://github.com/michpohl/Loopy/commit/fc464ce3da94bbec81dcc744089fa472292bbd10
Will have a look at the other issues you posted, and then merge into master and update the Play Store version as well.

**Comment by sagorahmed** [comment]
Hi @michpohl 
Thanks for solving this issue. Can't wait to check this app again after you publish an update.
